# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/blackstone/extract-files.sh

PRODUCT_COPY_FILES := \
    vendor/htc/blackstone/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so 

PRODUCT_COPY_FILES += \
    vendor/htc/blackstone/proprietary/sysinit:system/bin/sysinit \
    vendor/htc/blackstone/proprietary/libaudioeq.so:system/lib/libaudioeq.so 


PRODUCT_COPY_FILES += \
    vendor/htc/blackstone/proprietary/FOTAKill.apk:system/app/FOTAKill.apk \
    vendor/htc/blackstone/proprietary/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter.apk \
    vendor/htc/blackstone/proprietary/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk \
    vendor/htc/blackstone/proprietary/GoogleFeedback.apk:system/app/GoogleFeedback.apk \
    vendor/htc/blackstone/proprietary/GooglePartnerSetup.apk:system/app/GooglePartnerSetup.apk \
    vendor/htc/blackstone/proprietary/GoogleQuickSearchBox.apk:system/app/GoogleQuickSearchBox.apk \
    vendor/htc/blackstone/proprietary/GoogleServicesFramework.apk:system/app/GoogleServicesFramework.apk \
    vendor/htc/blackstone/proprietary/MarketUpdater.apk:system/app/MarketUpdater.apk \
    vendor/htc/blackstone/proprietary/MediaUploader.apk:system/app/MediaUploader.apk \
    vendor/htc/blackstone/proprietary/NetworkLocation.apk:system/app/NetworkLocation.apk \
    vendor/htc/blackstone/proprietary/OneTimeInitializer.apk:system/app/OneTimeInitializer.apk \
    vendor/htc/blackstone/proprietary/Vending.apk:system/app/Vending.apk \
    vendor/htc/blackstone/proprietary/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/htc/blackstone/proprietary/features.xml:system/etc/permissions/features.xml \
    vendor/htc/blackstone/proprietary/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/htc/blackstone/proprietary/libvoicesearch.so:system/lib/libvoicesearch.so

